package org.ldemetrios.kotlinpoet

import com.squareup.kotlinpoet.ClassName

public val BI_CONSUMER : ClassName = ClassName("java.util.function", "BiConsumer")
public val BI_FUNCTION : ClassName = ClassName("java.util.function", "BiFunction")
public val BINARY_OPERATOR : ClassName = ClassName("java.util.function", "BinaryOperator")
public val BI_PREDICATE : ClassName = ClassName("java.util.function", "BiPredicate")
public val BOOLEAN_SUPPLIER : ClassName = ClassName("java.util.function", "BooleanSupplier")
public val CONSUMER : ClassName = ClassName("java.util.function", "Consumer")
public val DOUBLE_BINARY_OPERATOR : ClassName = ClassName("java.util.function", "DoubleBinaryOperator")
public val DOUBLE_CONSUMER : ClassName = ClassName("java.util.function", "DoubleConsumer")
public val DOUBLE_FUNCTION : ClassName = ClassName("java.util.function", "DoubleFunction")
public val DOUBLE_PREDICATE : ClassName = ClassName("java.util.function", "DoublePredicate")
public val DOUBLE_SUPPLIER : ClassName = ClassName("java.util.function", "DoubleSupplier")
public val DOUBLE_TO_INT_FUNCTION : ClassName = ClassName("java.util.function", "DoubleToIntFunction")
public val DOUBLE_TO_LONG_FUNCTION : ClassName = ClassName("java.util.function", "DoubleToLongFunction")
public val DOUBLE_UNARY_OPERATOR : ClassName = ClassName("java.util.function", "DoubleUnaryOperator")
public val FUNCTION : ClassName = ClassName("java.util.function", "Function")
public val INT_BINARY_OPERATOR : ClassName = ClassName("java.util.function", "IntBinaryOperator")
public val INT_CONSUMER : ClassName = ClassName("java.util.function", "IntConsumer")
public val INT_FUNCTION : ClassName = ClassName("java.util.function", "IntFunction")
public val INT_PREDICATE : ClassName = ClassName("java.util.function", "IntPredicate")
public val INT_SUPPLIER : ClassName = ClassName("java.util.function", "IntSupplier")
public val INT_TO_DOUBLE_FUNCTION : ClassName = ClassName("java.util.function", "IntToDoubleFunction")
public val INT_TO_LONG_FUNCTION : ClassName = ClassName("java.util.function", "IntToLongFunction")
public val INT_UNARY_OPERATOR : ClassName = ClassName("java.util.function", "IntUnaryOperator")
public val LONG_BINARY_OPERATOR : ClassName = ClassName("java.util.function", "LongBinaryOperator")
public val LONG_CONSUMER : ClassName = ClassName("java.util.function", "LongConsumer")
public val LONG_FUNCTION : ClassName = ClassName("java.util.function", "LongFunction")
public val LONG_PREDICATE : ClassName = ClassName("java.util.function", "LongPredicate")
public val LONG_SUPPLIER : ClassName = ClassName("java.util.function", "LongSupplier")
public val LONG_TO_DOUBLE_FUNCTION : ClassName = ClassName("java.util.function", "LongToDoubleFunction")
public val LONG_TO_INT_FUNCTION : ClassName = ClassName("java.util.function", "LongToIntFunction")
public val LONG_UNARY_OPERATOR : ClassName = ClassName("java.util.function", "LongUnaryOperator")
public val OBJ_DOUBLE_CONSUMER : ClassName = ClassName("java.util.function", "ObjDoubleConsumer")
public val OBJ_INT_CONSUMER : ClassName = ClassName("java.util.function", "ObjIntConsumer")
public val OBJ_LONG_CONSUMER : ClassName = ClassName("java.util.function", "ObjLongConsumer")
public val PREDICATE : ClassName = ClassName("java.util.function", "Predicate")
public val SUPPLIER : ClassName = ClassName("java.util.function", "Supplier")
public val TO_DOUBLE_BI_FUNCTION : ClassName = ClassName("java.util.function", "ToDoubleBiFunction")
public val TO_DOUBLE_FUNCTION : ClassName = ClassName("java.util.function", "ToDoubleFunction")
public val TO_INT_BI_FUNCTION : ClassName = ClassName("java.util.function", "ToIntBiFunction")
public val TO_INT_FUNCTION : ClassName = ClassName("java.util.function", "ToIntFunction")
public val TO_LONG_BI_FUNCTION : ClassName = ClassName("java.util.function", "ToLongBiFunction")
public val TO_LONG_FUNCTION : ClassName = ClassName("java.util.function", "ToLongFunction")
public val UNARY_OPERATOR : ClassName = ClassName("java.util.function", "UnaryOperator")
